# This is a sample Dockerfile you can modify to deploy your own app based on face_recognition
# docker build -t jmcausing1/vfd .
#docker image push jmcausing1/vfd
#docker run -ti --entrypoint=/bin/bash -v /dev/video0:/dev/video0 313fd63b1c86


FROM arm32v7/python:3.7-slim-bullseye

RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN cd ~ && \
    mkdir -p dlib && \
    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS


RUN pip3 install face_recognition_models

RUN pip3 install Click>=6.0

RUN pip3 install dlib>=19.3.0

RUN pip3 install numpy

RUN pip3 install Pillow

#RUN pip3 install scipy>=0.17.0

# RUN pip3 install opencv-python -vv

# RUN cd ~ && \
#     mkdir -p vfd && \
#     git clone https://github.com/jmcausing/video_face_detect vfd/ && \
#     cd  vfd/ && \
#     pip3 install -r requirements.txt -vv 

CMD tail -f /dev/null